name = "ClusterDepth"
uuid = "c8d8bbfa-f476-4995-adff-2987f04015d1"
authors = ["Benedikt V. Ehinger"]
version = "0.1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Images = "0.25"
StatsBase = "0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
